# Generated by Django 2.1.1 on 2018-09-25 17:35

import admin_custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_model_register_app_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_custom.models.upload_image_path),
        ),
    ]
